well errors killing me
am gonna reinstall npm
error:
(node:3536) UnhandledPromiseRejectionWarning: TypeError: res.json is not a function
    at exports.removeCoffee (C:\Users\owner\Documents\C304Coffee\controllers\controller.js:134:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.